name: Pact-PHP Code Analysis & Test

on:
  push: 
  pull_request:
  # Once on the first of the month at 06:00 UTC
  schedule:
    - cron: 0 6 1 * *

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  php-cs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.2' ]

    steps:
      - uses: actions/checkout@v3
        name: Checkout repository

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - uses: ramsey/composer-install@v2
        with:
          dependency-versions: 'locked'

      - name: Code Style Analysis
        run: composer run lint

      - name: Static Code Analysis
        run: composer run static-code-analysis

  test:
    runs-on: ${{ matrix.operating-system }}
    needs:
      - php-cs
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macos-12, macos-14 ]
        php: [ '8.1', '8.2', '8.3' ]
        dependencies: [ 'lowest', 'locked' ]
    timeout-minutes: 5

    name: PHP ${{ matrix.php }} on ${{ matrix.operating-system }} with ${{ matrix.dependencies }} dependencies

    steps:
      - uses: actions/checkout@v3
        name: Checkout repository

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          extensions: ${{ matrix.operating-system == 'windows-latest' && contains('["8.2","8.3"]', matrix.php) && 'sockets, curl, zip, ffi' || 'sockets, curl, zip, ffi, grpc' }}
          php-version: ${{ matrix.php }}
          coverage: pcov
          ini-values: ${{ matrix.operating-system == 'windows-latest' && 'opcache.enable=0 opcache.enable_cli=0' || '' }}

      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install gRPC Extension (for PHP 8.2 & 8.3 on Windows)
        run: |
          cd C:\tools\php
          Invoke-WebRequest -Uri https://github.com/tienvx/build-php-grpc-extension/releases/download/builds/grpc_windows-2022_php-${{ matrix.php }}.dll -OutFile ext\php_grpc.dll
          echo "extension=php_grpc.dll" >> php.ini
        if: ${{ matrix.operating-system == 'windows-latest' && contains('["8.2","8.3"]', matrix.php) }}
        shell: pwsh

      - name: Composer install
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - name: Generate Library
        run: composer gen-lib

      - name: Run Tests
        run: vendor/bin/phpunit --debug
        env:
          PACT_DO_NOT_TRACK: true
